export const ActionTypes = {
  //Users
  LOGIN_USER: 'LOGIN_USER',
  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER',
  FAILED_USER: 'FAILED_USER',

  //Products
  GET_PRODUCTS: 'GET_PRODUCTS',
  FAILED_GET_PRODUCTS: 'FAILED_GET_PRODUCTS',

  //CART
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CHANGE_QTY: 'CHANGE_QTY',
  GET_CART_ITEMS: 'GET_CART_ITEMS',
  EMPTY_CART: 'EMPTY_CART',

  //Orders
  FAILED_Order: 'FAILED_Order',
};
